my_tuple = ()
print(my_tuple)
my_tuple = (1,2,3,4,5)
print(my_tuple)
my_tuple = (1, "Hello", 3.4)
print(my_tuple)
my_tuple = ("Fawaz", [3,4,5,6],(1,2,3,4,5,))
print(my_tuple)
my_tuple =('fawaz','ama ', "Meimuna" ,"Ali", 's')
print(my_tuple[0])
print(my_tuple[4])
n_tuple = ("Zakir", "Safian",(1,2,3,4,5,) ,[2,20,40,] )
print(n_tuple[2][3])
print(n_tuple[1][1])
print("sliced:", n_tuple[0:3])
